### ISSUE TITLE
examples and Usage

### ISSUE THREAD

**Issue by Neon22** [formix/infernal-engine#39]
This looks great and like it should solve my problem, if I can work out how to use it.
But I am having difficulty working that out.

**Problem:**
expert query system to ask questions and get responses and determine final set of parameters to make an object.
E.g. Rules:
1. Item cannot be longer than 44 or less than 20
2. options for curved edges [None, 1,2,3]
3. if item is > 36 then curved edge option must not be 3
4. option for extra holes [None, 4,5,6]
5. if option 2 then valid holes are [None, 4]
6. if option 2 and option 4 then length must be <24

How do I wrap this so I can ask a Q, then work out which Q to ask next ?
and so on - so I always have a correct and valid state ?
And have I omitted to ask you something that needs to be asked in order to do this ?

**Comment by formix** [comment]
Hi @Neon22, sorry for the late response. I will do an example model for you and that will give you a good idea on how it works. But basically, there is no structural constraints to the model you do so you need to devise a modeling structure yourself. The example will cover that as well.

**Comment by formix** [comment]
Ok, I created an incomplete untested gist to give you an idea of how things goes with your request. Doing a configurable model is relatively easy but takes time it is normal. A lot of checks needs to be made in order to guarantee that everything is always valid and to report invalid state properly.

I still need to create a rule to make the option "3" unavailable when the item length is greater than 36, and everything else...

I'll update you when I get the gist updated:
https://gist.github.com/formix/e2238022d0a2a72ddef908acb98ca34b

**Comment by Neon22** [comment]
I only just recievd the notifiaction and that it was closed. (Probably email lossage my end, sorry for not responding sooner).
Thanks so much for trying to help me with this. I will use your example and continue my experiments.

**Comment by formix** [comment]
Great! I'm happy it could help. Stay in touch with me and continue asking questions. I'll be pleased to help you out at every steps of your project.

Thanks!
